### ISSUE TITLE
Add build folder to git ignore

### ISSUE THREAD

**Issue by mahirk** [dubhacks/15f#11]
@grant it seems like if I add the build folder in gitignore it would still work as its updated everytime i run it

Can we add it to the gitignore and rm it from github? It'll still build on the main server

cc: #2

**Comment by karan** [comment]
If you `gitignore` `build/`, it will be left out from the `gh-pages` branch and give 404's. (Because [we serve from `build/`](https://github.com/dubhacks/15f/blob/gh-pages/index.html#L21)).

An alternative could be to have a `master` branch that ignores the `build` folder and a `Makefile` or something that builds everything and pushes what needs to be served to `gh-pages`. Over-engineering for this use case IMO.

**Comment by mahirk** [comment]
@karan I was just about to close this issue, hadn't seen the main page, thought it was being rebuilt by the server, wasn't sure if it was still hosted on git pages
